/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wAdeDCLycxi
 */
import { AlertTitle, AlertDescription, Alert } from "@/components/ui/alert"


interface DynamicAlertProps {
  type: 'success' | 'warning' | 'error';
  title: string;
  description: string;
}


export function DynamicAlert({ type, title, description }: DynamicAlertProps) {
  let variant: "warning" | "default" | "destructive" | null = null;

  switch (type) {
    case 'success':
      variant = 'default'; 
      break;
    case 'warning':
      variant = 'warning';
      break;
    case 'error':
      variant = 'destructive';
      break;
    default:
      variant = 'default'; 
      break;
  }

  return (
    <Alert className="fixed top-4 right-6 w-auto" variant={variant}>
      <AlertTitle>{title}</AlertTitle>
      <AlertDescription>{description}</AlertDescription>
    </Alert>
  );
}
