/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Rsl8vCJduMh
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-12 space-y-4 text-center lg:grid lg:gap-0 lg:grid-cols-2">
      <div className="hidden lg:flex flex-col items-center justify-center space-y-2">
        <img
          alt="Image"
          className="rounded-full"
          height="400"
          src="/placeholder.svg"
          style={{
            aspectRatio: "400/400",
            objectFit: "cover",
          }}
          width="400"
        />
        <div className="space-y-2">
          <h1 className="text-3xl font-bold">Welcome to Pets</h1>
          <p className="text-gray-500 dark:text-gray-400">Pet management app</p>
        </div>
      </div>
      <div className="w-full max-w-sm space-y-4">
        <div className="space-y-4 text-center">
          <h1 className="text-3xl font-bold">Login</h1>
          <p className="text-gray-500 dark:text-gray-400">Enter your email below to login to your account</p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="m@example.com" required type="email" />
          </div>
          <div className="space-y-2">
            <div className="flex items-center">
              <Label htmlFor="password">Password</Label>
              <Link className="ml-auto inline-block text-sm underline" to ="#">
                Forgot your password?
              </Link>
            </div>
            <Input id="password" required type="password" />
          </div>
          <Button className="w-full" type="submit">
            Login
          </Button>
          <Button className="w-full" variant="outline">
            Login with Google
          </Button>
        </div>
        <div className="mt-4 text-center text-sm">
          Don't have an account?
          <Link className="underline" to ="#">
            Sign up
          </Link>
        </div>
      </div>
    </div>
  )
}
