/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/H5zd3ZlBWO6
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import React , { SVGProps } from 'react';

export function petsView() {
  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center px-4 py-2 border-b lg:px-6">
        <div className="space-y-1">
          <h1 className="text-lg font-bold tracking-wide">Pet Connections & Profiles</h1>
          <div className="flex w-full max-w-md rounded-lg bg-gray-100 dark:bg-gray-800">
            <SearchIcon className="w-4 h-4 mx-2" />
            <Input
              className="w-full bg-transparent focus:outline-none dark:placeholder-gray-400"
              placeholder="Search for pet owners..."
              type="search"
            />
          </div>
        </div>
      </div>
      <div className="flex-1 overflow-y-auto p-4 lg:p-6">
        <div className="grid gap-4 md:grid-cols-2 lg:gap-6">
          <div className="flex items-start gap-4">
            <img
              alt="Dog profile picture"
              className="rounded-full"
              height="80"
              src="/placeholder.svg"
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width="80"
            />
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-semibold">Max the Labrador</h2>
                <Button size="sm">View Profile</Button>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Loves long walks and playing fetch</p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <img
              alt="Dog profile picture"
              className="rounded-full"
              height="80"
              src="/placeholder.svg"
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width="80"
            />
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-semibold">Bella the Poodle</h2>
                <Button size="sm">View Profile</Button>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Enjoys cuddles and chasing squirrels</p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <img
              alt="Dog profile picture"
              className="rounded-full"
              height="80"
              src="/placeholder.svg"
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width="80"
            />
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-semibold">Rocky the Bulldog</h2>
                <Button size="sm">View Profile</Button>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Enthusiastic about treats and belly rubs</p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <img
              alt="Dog profile picture"
              className="rounded-full"
              height="80"
              src="/placeholder.svg"
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width="80"
            />
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-semibold">Luna the Husky</h2>
                <Button size="sm">View Profile</Button>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Enjoys the snow and long runs</p>
            </div>
          </div>
        </div>
        <div className="grid gap-4 md:grid-cols-2 lg:gap-6">
          <div className="flex items-start gap-4">
            <img
              alt="Dog profile picture"
              className="rounded-full"
              height="80"
              src="/placeholder.svg"
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width="80"
            />
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-semibold">Cooper the Golden Retriever</h2>
                <Button size="sm">View Profile</Button>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Water enthusiast and tennis ball lover</p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <img
              alt="Dog profile picture"
              className="rounded-full"
              height="80"
              src="/placeholder.svg"
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width="80"
            />
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-semibold">Daisy the Dachshund</h2>
                <Button size="sm">View Profile</Button>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Loves sunbathing and digging holes</p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <img
              alt="Dog profile picture"
              className="rounded-full"
              height="80"
              src="/placeholder.svg"
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width="80"
            />
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-semibold">Bailey the Beagle</h2>
                <Button size="sm">View Profile</Button>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Sniffing expert and food connoisseur</p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <img
              alt="Dog profile picture"
              className="rounded-full"
              height="80"
              src="/placeholder.svg"
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width="80"
            />
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-semibold">Milo the Maltese</h2>
                <Button size="sm">View Profile</Button>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">Fluffy and friendly companion</p>
            </div>
          </div>
        </div>
      </div>
      <div className="flex items-center justify-center p-4 border-t sm:p-6">
        <Button className="h-10 m-1" variant="outline">
          Load More
        </Button>
      </div>
    </div>
  )
}


function SearchIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}